const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('petAPI', {
  getClipboard: () => ipcRenderer.invoke('get-clipboard'),
  loadData: () => ipcRenderer.invoke('load-data'),
  saveData: (data) => ipcRenderer.invoke('save-data', data),
  restoreBackup: (backup) => ipcRenderer.invoke('restore-backup', backup),
  hideWindow: () => ipcRenderer.invoke('window-hide'),
  setWindowMode: (mode) => ipcRenderer.invoke('set-window-mode', mode),
  getWindowPosition: () => ipcRenderer.invoke('get-window-position'),
  setWindowPosition: (x, y) => ipcRenderer.invoke('set-window-position', x, y),
  beginWindowDrag: () => ipcRenderer.invoke('begin-window-drag'),
  endWindowDrag: () => ipcRenderer.invoke('end-window-drag'),
  getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
  lookupOnline: (word) => ipcRenderer.invoke('lookup-online', word),
  translateText: (text) => ipcRenderer.invoke('translate-text', text),
  getSyncStatus: () => ipcRenderer.invoke('sync-status'),
  setSyncServer: (opts) => ipcRenderer.invoke('sync-server-set', opts),
  refreshSyncCode: () => ipcRenderer.invoke('sync-refresh-code'),
  selectSyncIp: (ip) => ipcRenderer.invoke('sync-select-ip', ip),
  allowSyncFirewall: () => ipcRenderer.invoke('sync-allow-firewall'),
  removeSyncDevice: (deviceId) => ipcRenderer.invoke('sync-remove-device', deviceId),
  recordWordDelete: (payload) => ipcRenderer.invoke('sync-record-delete', payload),
  recordWordDeletes: (list) => ipcRenderer.invoke('sync-record-deletes', list),
  onSyncDataUpdated: (callback) => ipcRenderer.on('sync-data-updated', callback),
  onShortcut: (callback) => ipcRenderer.on('shortcut-summon', callback),
  onShortcutHide: (callback) => ipcRenderer.on('shortcut-hide-panel', callback),
  onPetShown: (callback) => ipcRenderer.on('pet-shown', callback)
});
